services:
  mongo:
    image: mongodb/atlas
    privileged: true
    volumes:
      - data-cni:/etc/cni
      - data-containers:/var/lib/containers
      - ./mongo-entrypoint.sh:/entrypoint.sh
    entrypoint: ["/entrypoint.sh"]
    ports:
      - 27017:27017
    environment:
      - LOCALDEV_PASSWORD=password
  py-jit:
    build: ./py-jit
    ports:
      - 5000:5000
volumes:
  data-cni:
  data-containers:
